### ISSUE TITLE
the pictures in the paper

### ISSUE THREAD

**Issue by henbucuoshanghai** [zeiss-microscopy/BSConv#2]
![image](https://user-images.githubusercontent.com/37647094/84012053-8ee28b00-a9a9-11ea-8430-3f7722326537.png)

how  to get this??where is the code?

**Comment by henbucuoshanghai** [comment]
Figure 3   how to get it?

**Comment by zeiss-mamthor** [comment]
Currently, we are focusing on model implementations and training. Code for reproducing figures might be added later. However, the methodology is described in detail on page 3 (left column) in the paper.

**Comment by chuong98** [comment]
@zeiss-dhaase @zeiss-mamthor Hi, can you help to clarify how to calculate the variance:

> For each individual filter of the CNN, we:
> 1. split the M ×K ×K kernel into M samples of size K ×K, 
> 2. perform principal component analysis (PCA) on the set of M samples
> 3. determine the variance of the filter kernel which is explained by the first principal component (PC1).

Step 1 and 2 is clear, but I am not quite understand the step 3.
Let say after Step 2, you get M pca-components of vector size 1 x K^2. 
Then how do you define the variance? Do you use PC1 as the mean vector, or on what set?
Thank you.

**Comment by zeiss-dhaase** [comment]
Here is some pseudo-code that should clarify the calculation:

For every `CxHxW` kernel `F` of a layer of a CNN, we calculate:
```
# step 1: split 3D kernel F into 2D kernels (assuming F is of size CxHxW)
xs = [F[nChannel, :, :].flatten() for nChannel in range(F.shape[0])]
X = np.array(xs)

# step 2: perform PCA
import sklearn.decomposition        
pca = sklearn.decomposition.PCA(n_components=None)
pca.fit(X)

# step3: this is the variance of F which is explained by the first principal component (PC1)
v = pca.explained_variance_ratio_[0]
```

Figure 3 of the paper just plots the variances of all filters as a histogram. The colors indicate the network stage of the filters (stage1, 2, 3, or 4).
