### ISSUE TITLE
How is BSConv being utilized in MobileNet V2 and V3?

### ISSUE THREAD

**Issue by boenshao** [zeiss-microscopy/BSConv#3]
Great paper!
Just one small question,
It seems that you have not alter the structure of mobilenet v2 and v3, because it sort of already got BSConv built in?
Dose this imply that the accuracy gain (especially in CIFAR) is purely from the proposed orthonormal regularization loss?

**Comment by zeiss-mamthor** [comment]
Thank you!
Yes, we decided for keeping the entire structure of MobileNet V2 and V3 as they can be reinterpreted as a BSConv-S model as shown in Sect. 4.2 in the paper. As you have already observed correctly, for those models, the resulting performance gain entirely results from the regularization loss.
